import type { VideoSource } from '@/lib/types';

// Default predefined video sources - Real Chinese video APIs
// Note: searchPath and detailPath should not contain query params as they are added by the API code
export const DEFAULT_SOURCES: VideoSource[] = [
  {
    id: 'dytt',
    name: '电影天堂资源',
    baseUrl: 'http://caiji.dyttzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 1,
    group: 'normal',
  },
  {
    id: 'ffzy',
    name: '非凡资源',
    baseUrl: 'http://ffzy3.tv',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 2,
    group: 'normal',
  },
  {
    id: 'hongniu',
    name: '红牛资源',
    baseUrl: 'https://www.hongniuzy2.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 3,
    group: 'normal',
  },
  {
    id: 'maoyan',
    name: '猫眼资源',
    baseUrl: 'https://api.maoyanapi.top',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 4,
    group: 'normal',
  },
  {
    id: 'ruyi',
    name: '如意资源',
    baseUrl: 'https://cj.rycjapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 5,
    group: 'normal',
  },
  {
    id: 'ikun',
    name: 'iKun资源',
    baseUrl: 'https://ikunzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 6,
    group: 'normal',
  },
  {
    id: 'p2100',
    name: 'p2100影视',
    baseUrl: 'https://p2100.net',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 7,
    group: 'normal',
  },
  {
    id: 'huya',
    name: '虎牙资源',
    baseUrl: 'https://www.huyaapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 8,
    group: 'normal',
  },
  {
    id: 'modu',
    name: '魔都资源',
    baseUrl: 'https://www.mdzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 9,
    group: 'normal',
  },
];
