import type { VideoSource } from '@/lib/types';

// Default predefined video sources - Real Chinese video APIs
export const DEFAULT_SOURCES: VideoSource[] = [
  {
    id: 'heimuer',
    name: '黑木耳',
    baseUrl: 'https://json.heimuer.one',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 1,
    group: 'normal',
  },
  {
    id: 'ffzy',
    name: '非凡资源',
    baseUrl: 'https://cj.ffzyapi.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 2,
    group: 'normal',
  },
  {
    id: 'hongniu',
    name: '红牛资源',
    baseUrl: 'https://www.hongniuzy2.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 3,
    group: 'normal',
  },
  {
    id: 'hnm3u8',
    name: '红牛m3u8',
    baseUrl: 'https://www.hongniuzy5.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 4,
    group: 'normal',
  },
  {
    id: 'wolong',
    name: '卧龙资源',
    baseUrl: 'https://collect.wolongzy.cc',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 5,
    group: 'normal',
  },
  {
    id: 'ikun',
    name: 'iKun资源',
    baseUrl: 'https://ikunzyapi.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 6,
    group: 'normal',
  },
  {
    id: 'jisu',
    name: '极速资源',
    baseUrl: 'https://jszyapi.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 7,
    group: 'normal',
  },
  {
    id: 'dbzy',
    name: '多播资源',
    baseUrl: 'https://dbzy.cc',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 8,
    group: 'normal',
  },
  {
    id: 'mdzy',
    name: '魔都资源',
    baseUrl: 'https://api.moduvip.com',
    searchPath: '/api.php/provide/vod/?ac=detail&wd=',
    detailPath: '/api.php/provide/vod/?ac=detail&ids=',
    enabled: true,
    priority: 9,
    group: 'normal',
  },
  {
    id: 'tpzy',
    name: '淘片资源',
    baseUrl: 'https://taopianapi.com',
    searchPath: '/home/cjapi/vod/mc/10/wd/',
    detailPath: '/home/cjapi/vod/mc/10/id/',
    enabled: true,
    priority: 10,
    group: 'normal',
  },
];
