import type { VideoSource } from '@/lib/types';

// Premium video sources - require unlock key to access
// These sources are hidden by default and require key verification
export const PREMIUM_SOURCES: VideoSource[] = [
  {
    id: 'kuaibo',
    name: '快播资源',
    baseUrl: 'https://www.kuaibozy.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 10,
    group: 'premium',
  },
  {
    id: 'shandian',
    name: '闪电资源',
    baseUrl: 'https://sdzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 11,
    group: 'premium',
  },
  {
    id: 'guangsu',
    name: '光速资源',
    baseUrl: 'https://api.guangsuapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 12,
    group: 'premium',
  },
  {
    id: 'xinlang',
    name: '新浪资源',
    baseUrl: 'https://api.xinlangapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 13,
    group: 'premium',
  },
  {
    id: 'tiankong',
    name: '天空资源',
    baseUrl: 'https://api.tiankongapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 14,
    group: 'premium',
  },
  {
    id: 'kudian',
    name: '酷点资源',
    baseUrl: 'https://api.kudian10.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 15,
    group: 'premium',
  },
  {
    id: 'baidu',
    name: '百度资源',
    baseUrl: 'https://api.apibdzy.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 16,
    group: 'premium',
  },
  {
    id: 'zuida',
    name: '最大资源',
    baseUrl: 'https://api.zuidapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 17,
    group: 'premium',
  },
  {
    id: 'yule',
    name: '鱼乐资源',
    baseUrl: 'https://api.ylzy1.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 18,
    group: 'premium',
  },
  {
    id: 'fanqie',
    name: '番茄资源',
    baseUrl: 'https://api.fqzy.cc',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 19,
    group: 'premium',
  },
  {
    id: 'taopian',
    name: '淘片资源',
    baseUrl: 'https://taopianapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 20,
    group: 'premium',
  },
  {
    id: 'wujin',
    name: '无尽资源',
    baseUrl: 'https://api.wujinapi.me',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 21,
    group: 'premium',
  },
  {
    id: 'baofeng',
    name: '暴风资源',
    baseUrl: 'https://bfzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 22,
    group: 'premium',
  },
  {
    id: 'feisu',
    name: '飞速资源',
    baseUrl: 'https://www.feisuzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 23,
    group: 'premium',
  },
  {
    id: 'liangzi',
    name: '量子资源',
    baseUrl: 'https://cj.lziapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 24,
    group: 'premium',
  },
  {
    id: 'suoni',
    name: '索尼资源',
    baseUrl: 'https://suoniapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 25,
    group: 'premium',
  },
];
