import type { VideoSource } from '@/lib/types';

// Premium video sources - require unlock key to access
// These sources are hidden by default and require key verification
export const PREMIUM_SOURCES: VideoSource[] = [
  {
    id: 'xigua',
    name: '西瓜资源',
    baseUrl: 'https://caiji.xgzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 10,
    group: 'premium',
  },
  {
    id: '360zy',
    name: '360资源',
    baseUrl: 'https://360zyzz.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 11,
    group: 'premium',
  },
  {
    id: 'guangsu',
    name: '光速资源',
    baseUrl: 'https://api.guangsuapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 12,
    group: 'premium',
  },
  {
    id: 'dazhong',
    name: '大众资源',
    baseUrl: 'https://cdn.dzzyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 13,
    group: 'premium',
  },
  {
    id: 'haohua',
    name: '豪华资源',
    baseUrl: 'https://haohuazy.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 14,
    group: 'premium',
  },
  {
    id: 'moduapi',
    name: '魔都资源(moduapi)',
    baseUrl: 'https://caiji.moduapi.cc',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 15,
    group: 'premium',
  },
  {
    id: 'baidu',
    name: '百度资源',
    baseUrl: 'https://api.apibdzy.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 16,
    group: 'premium',
  },
  {
    id: 'zuida',
    name: '最大资源',
    baseUrl: 'https://api.zuidapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 17,
    group: 'premium',
  },
  {
    id: 'yinghua',
    name: '樱花资源',
    baseUrl: 'https://yhzy.cc',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 18,
    group: 'premium',
  },
  {
    id: 'iqiyi',
    name: '爱奇艺资源',
    baseUrl: 'https://www.iqiyizyapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 19,
    group: 'premium',
  },
  {
    id: 'hongniuzy3',
    name: '红牛资源(hongniuzy3)',
    baseUrl: 'https://www.hongniuzy3.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 20,
    group: 'premium',
  },
  {
    id: 'wujin',
    name: '无尽资源',
    baseUrl: 'https://api.wujinapi.me',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 21,
    group: 'premium',
  },
  {
    id: 'uku',
    name: 'uku资源',
    baseUrl: 'https://api.ukuapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 22,
    group: 'premium',
  },
  {
    id: 'hongniuzy4',
    name: '红牛资源(hongniuzy4)',
    baseUrl: 'https://www.hongniuzy4.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 23,
    group: 'premium',
  },
  {
    id: 'liangzi',
    name: '量子资源',
    baseUrl: 'https://cj.lziapi.com',
    searchPath: '/api.php/provide/vod/',
    detailPath: '/api.php/provide/vod/',
    enabled: true,
    priority: 24,
    group: 'premium',
  },
];
